package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"sync"

	"github.com/vibeserve/vibeserve/internal/llm"
)

// ProxyEngine intercepts unmatched HTTP requests and auto-generates API endpoints
// using the LLM. Each new request potentially creates new routes and tables,
// building up a complete API map incrementally.
type ProxyEngine struct {
	engine   *Engine
	provider llm.Provider
	bus      *Bus

	// mu protects pending to prevent duplicate route generation for concurrent requests.
	mu      sync.Mutex
	pending map[string]chan proxyResult // key: "METHOD /path"
}

// proxyResult carries the outcome of a proxy generation attempt.
type proxyResult struct {
	StatusCode int
	Body       map[string]any
	Headers    map[string]string
	Err        error
}

// NewProxyEngine creates a new ProxyEngine backed by the given Engine.
func NewProxyEngine(eng *Engine) *ProxyEngine {
	return &ProxyEngine{
		engine:   eng,
		provider: eng.Provider(),
		bus:      eng.Bus(),
		pending:  make(map[string]chan proxyResult),
	}
}

// HandleUnknownRequest is called when a request hits an unmatched route.
// It analyzes the request, uses the LLM to generate the API, registers it,
// and returns a response.
func (pe *ProxyEngine) HandleUnknownRequest(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, headers map[string]string) (int, map[string]any, map[string]string, error) {
	key := method + " " + path

	// Check if this route is already being generated by another goroutine.
	pe.mu.Lock()
	if ch, ok := pe.pending[key]; ok {
		// Another goroutine is generating this route. Wait for it.
		pe.mu.Unlock()
		result := <-ch
		return result.StatusCode, result.Body, result.Headers, result.Err
	}

	// Mark this route as being generated.
	ch := make(chan proxyResult, 1)
	pe.pending[key] = ch
	pe.mu.Unlock()

	// Generate the route.
	status, respBody, respHeaders, err := pe.generateRoute(ctx, method, path, body, queryParams)

	// Store the result for any waiters.
	result := proxyResult{
		StatusCode: status,
		Body:       respBody,
		Headers:    respHeaders,
		Err:        err,
	}

	// Clean up pending entry.
	pe.mu.Lock()
	delete(pe.pending, key)
	pe.mu.Unlock()

	// Send result to any waiters.
	ch <- result

	return status, respBody, respHeaders, err
}

// generateRoute builds a prompt from the request and calls the LLM to generate the endpoint.
func (pe *ProxyEngine) generateRoute(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string) (int, map[string]any, map[string]string, error) {
	prompt := pe.BuildPromptFromRequest(method, path, body, queryParams)

	log.Printf("[proxy] Generating endpoint for %s %s", method, path)
	pe.bus.Publish(Event{Type: EventLLMRequestStarted, Data: fmt.Sprintf("Generating %s %s...", method, path)})

	result, err := pe.engine.ApplyAutoApprove(ctx, prompt)
	if err != nil {
		log.Printf("[proxy] Generation failed for %s %s: %v", method, path, err)
		pe.bus.Publish(Event{Type: EventLLMRequestCompleted})
		return 500, map[string]any{
			"error":   "auto-generation failed",
			"detail":  err.Error(),
			"method":  method,
			"path":    path,
		}, nil, nil
	}

	pe.bus.Publish(Event{Type: EventLLMRequestCompleted})

	log.Printf("[proxy] Successfully generated %s %s (%d changes)", method, path, len(result.Changes))

	// Now execute the newly registered script for the original request.
	return pe.executeGeneratedRoute(method, path, body, queryParams)
}

// executeGeneratedRoute runs the script for the given route after it's been registered.
func (pe *ProxyEngine) executeGeneratedRoute(method, path string, body map[string]any, queryParams map[string]string) (int, map[string]any, map[string]string, error) {
	// Import the runtime package is tricky due to import cycles.
	// Instead, we return a special signal to the handler so it re-looks up
	// the route in the trie and executes the script through the normal path.
	// We use a sentinel response that the proxy handler recognizes.
	return 0, map[string]any{
		"__vibeserve_retry__": true,
	}, map[string]string{
		"X-VibeServe-Generated": "true",
	}, nil
}

// BuildPromptFromRequest constructs a natural language prompt describing what API to create,
// based on the HTTP method, path, body, and query parameters of the incoming request.
func (pe *ProxyEngine) BuildPromptFromRequest(method, path string, body map[string]any, queryParams map[string]string) string {
	var b strings.Builder

	// Derive resource name from path
	resource := pathToResource(path)

	b.WriteString(fmt.Sprintf("Create a REST API endpoint for %s %s. ", method, path))

	// Describe the resource
	if resource != "" {
		b.WriteString(fmt.Sprintf("The resource is \"%s\". ", resource))
	}

	// Describe what the method implies
	switch method {
	case "GET":
		if strings.Contains(path, ":") || strings.Contains(path, "/") && countSegments(path) > 1 {
			b.WriteString("This should retrieve a single item by ID. ")
		} else {
			b.WriteString("This should list all items. ")
		}
	case "POST":
		b.WriteString("This should create a new item. ")
	case "PUT", "PATCH":
		b.WriteString("This should update an existing item. ")
	case "DELETE":
		b.WriteString("This should delete an item. ")
	}

	// Include body fields as column hints
	if len(body) > 0 {
		b.WriteString("The request body contains these fields: ")
		fields := describeFields(body)
		b.WriteString(fields)
		b.WriteString(". ")
	}

	// Include query parameters
	if len(queryParams) > 0 {
		b.WriteString("Query parameters: ")
		first := true
		for k, v := range queryParams {
			if !first {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%s (example value: %s)", k, v))
			first = false
		}
		b.WriteString(". Support filtering by these parameters. ")
	}

	// Include existing manifest context
	currentManifest := pe.engine.Manifest()
	if currentManifest != nil && len(currentManifest.Routes) > 0 {
		b.WriteString("\n\nIMPORTANT: The API already has these routes: ")
		for i, r := range currentManifest.Routes {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%s %s", r.Method, r.Path))
		}
		b.WriteString(". Preserve ALL existing routes, schemas, scripts, and seeds. Only ADD new ones. ")
	}

	// Generate sensible defaults
	b.WriteString("\n\nRequirements:\n")
	b.WriteString("- Include an auto-increment id primary key column\n")
	b.WriteString("- Include a created_at DATETIME column with default NOW\n")

	// Generate CRUD for the resource if not already present
	if resource != "" {
		b.WriteString(fmt.Sprintf("- Generate full CRUD for %s (GET list, GET by id, POST create, PUT update, DELETE)\n", resource))
	}

	b.WriteString("- Output ONLY the complete manifest JSON\n")

	return b.String()
}

// pathToResource extracts a resource name from a URL path.
// e.g., "/users" -> "users", "/users/:id" -> "users", "/users/:id/posts" -> "user_posts"
func pathToResource(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	// Filter out param segments
	var resources []string
	for _, p := range parts {
		if p == "" || strings.HasPrefix(p, ":") {
			continue
		}
		resources = append(resources, p)
	}
	if len(resources) == 0 {
		return ""
	}
	// Use the last non-param segment as the resource name
	return resources[len(resources)-1]
}

// countSegments returns the number of path segments.
func countSegments(path string) int {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	count := 0
	for _, p := range parts {
		if p != "" {
			count++
		}
	}
	return count
}

// describeFields generates a description of JSON body fields with type guesses.
func describeFields(body map[string]any) string {
	var parts []string
	for k, v := range body {
		goType := guessType(v)
		parts = append(parts, fmt.Sprintf("%s (%s)", k, goType))
	}
	return strings.Join(parts, ", ")
}

// guessType maps a Go value to a manifest column type.
func guessType(v any) string {
	switch v.(type) {
	case float64:
		// JSON numbers are float64 by default
		if v.(float64) == float64(int(v.(float64))) {
			return "INTEGER"
		}
		return "REAL"
	case int, int64:
		return "INTEGER"
	case string:
		return "TEXT"
	case bool:
		return "BOOLEAN"
	case []any:
		return "TEXT" // Store arrays as JSON text
	case map[string]any:
		return "TEXT" // Store objects as JSON text
	case nil:
		return "TEXT"
	default:
		// Try to serialize as JSON for type detection
		b, err := json.Marshal(v)
		if err == nil {
			var parsed any
			if json.Unmarshal(b, &parsed) == nil {
				return guessType(parsed)
			}
		}
		return "TEXT"
	}
}
