package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"sync"
	"time"

	"github.com/vibeserve/vibeserve/internal/manifest"
)

const (
	proxyRateLimit  = 30          // max generations per window
	proxyRateWindow = time.Minute // window duration
)

// ProxyEngine intercepts unmatched HTTP requests and intelligently generates
// API endpoints. It uses a 3-phase approach:
//
//  1. Analyze intent — what does the user want? (deterministic, no AI)
//  2. Check existing schema — can we map to an existing table?
//  3. Generate — fast-path for obvious cases, AI for ambiguous ones
//
// This builds up a coherent database over time. Tables get linked via foreign
// keys, columns evolve as new fields appear, and relationship routes are
// detected automatically.
type ProxyEngine struct {
	engine *Engine

	// mu protects pending to prevent duplicate route generation for concurrent requests.
	mu      sync.Mutex
	pending map[string]chan proxyResult // key: "METHOD /path"

	// Rate limiting for route generation.
	rateMu      sync.Mutex
	genCount    int       // generations in current window
	windowStart time.Time // start of current rate limit window
}

// proxyResult carries the outcome of a proxy generation attempt.
type proxyResult struct {
	StatusCode int
	Body       map[string]any
	Headers    map[string]string
	Err        error
}

// NewProxyEngine creates a new ProxyEngine backed by the given Engine.
func NewProxyEngine(eng *Engine) *ProxyEngine {
	return &ProxyEngine{
		engine:      eng,
		pending:     make(map[string]chan proxyResult),
		windowStart: time.Now(),
	}
}

// HandleUnknownRequest is called when a request hits an unmatched route.
// It analyzes the request intent, generates the appropriate API changes,
// and returns a response.
func (pe *ProxyEngine) HandleUnknownRequest(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, headers map[string]string) (int, map[string]any, map[string]string, error) {
	key := method + " " + path

	// Check if this route is already being generated by another goroutine.
	pe.mu.Lock()
	if ch, ok := pe.pending[key]; ok {
		pe.mu.Unlock()
		result := <-ch
		return result.StatusCode, result.Body, result.Headers, result.Err
	}

	// Mark this route as being generated.
	ch := make(chan proxyResult, 1)
	pe.pending[key] = ch
	pe.mu.Unlock()

	// Generate the route.
	status, respBody, respHeaders, err := pe.smartGenerate(ctx, method, path, body, queryParams)

	result := proxyResult{
		StatusCode: status,
		Body:       respBody,
		Headers:    respHeaders,
		Err:        err,
	}

	pe.mu.Lock()
	delete(pe.pending, key)
	pe.mu.Unlock()

	ch <- result
	return status, respBody, respHeaders, err
}

// checkRateLimit returns an error if the generation rate limit has been exceeded.
func (pe *ProxyEngine) checkRateLimit() error {
	pe.rateMu.Lock()
	defer pe.rateMu.Unlock()

	now := time.Now()
	if now.Sub(pe.windowStart) > proxyRateWindow {
		// Reset window.
		pe.windowStart = now
		pe.genCount = 0
	}

	if pe.genCount >= proxyRateLimit {
		return fmt.Errorf("rate limit exceeded: max %d route generations per minute", proxyRateLimit)
	}

	pe.genCount++
	return nil
}

// smartGenerate is the core of the intent-aware proxy.
// Phase 1: Analyze intent (deterministic, instant)
// Phase 2: Execute based on intent type
func (pe *ProxyEngine) smartGenerate(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string) (int, map[string]any, map[string]string, error) {
	if err := pe.checkRateLimit(); err != nil {
		return 429, map[string]any{"error": err.Error()}, nil, nil
	}

	currentManifest := pe.engine.Manifest()

	// Phase 1: Analyze intent
	analyzer := NewIntentAnalyzer(currentManifest)
	intent := analyzer.Analyze(method, path, body, queryParams)

	log.Printf("[proxy] Intent: %s for %s %s (resource=%s)", intent.Type, method, path, intent.Resource)

	switch intent.Type {
	case IntentCreateTable:
		return pe.handleCreateTable(ctx, method, path, body, intent)

	case IntentAddRoute:
		return pe.handleAddRoute(ctx, method, path, body, intent)

	case IntentAddColumn:
		return pe.handleAddColumn(ctx, method, path, body, intent)

	case IntentAddRelationshipRoute:
		return pe.handleRelationshipRoute(ctx, method, path, body, queryParams, intent)

	case IntentAI:
		return pe.handleAI(ctx, method, path, body, queryParams, intent)

	default:
		return 500, map[string]any{"error": "unknown intent type"}, nil, nil
	}
}

// handleCreateTable uses the LLM to design a proper table with appropriate
// columns, types, constraints, and foreign keys to existing tables.
// The LLM sees the full current schema context and designs a well-structured table.
func (pe *ProxyEngine) handleCreateTable(ctx context.Context, method, path string, body map[string]any, intent *Intent) (int, map[string]any, map[string]string, error) {
	tableName := intent.TableName
	log.Printf("[proxy] Creating table %s via LLM", tableName)

	// Build a context-aware prompt for the LLM
	analyzer := NewIntentAnalyzer(pe.engine.Manifest())
	prompt := analyzer.BuildSmartPrompt(method, path, body, nil)

	// Let the LLM design the complete schema + routes
	result, err := pe.engine.ApplyAutoApprove(ctx, prompt)
	if err != nil {
		log.Printf("[proxy] LLM table creation failed: %v", err)
		return 500, map[string]any{
			"error":  "failed to create table",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Created table %s via LLM (%d changes)", tableName, len(result.Changes))
	return retryResponse()
}

// handleAddRoute maps a new path to an existing table. No schema changes needed.
func (pe *ProxyEngine) handleAddRoute(ctx context.Context, method, path string, body map[string]any, intent *Intent) (int, map[string]any, map[string]string, error) {
	tableName := intent.TargetTable
	log.Printf("[proxy] Adding route %s %s -> existing table %s", method, path, tableName)

	currentManifest := pe.engine.Manifest()
	newManifest := copyManifest(currentManifest)

	// Add the custom route pointing to the existing table
	route, script := generateCustomRoute(method, path, tableName, body)
	newManifest.Routes = append(newManifest.Routes, route)
	newManifest.Scripts = append(newManifest.Scripts, script)

	prompt := fmt.Sprintf("Add route %s %s mapping to table %s", method, path, tableName)
	result, err := pe.engine.ApplyManifestDirect(ctx, prompt, newManifest)
	if err != nil {
		return 500, map[string]any{
			"error":  "failed to add route",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Added route %s %s (%d changes)", method, path, len(result.Changes))
	return retryResponse()
}

// handleAddColumn uses the LLM to add new columns with proper types and constraints.
func (pe *ProxyEngine) handleAddColumn(ctx context.Context, method, path string, body map[string]any, intent *Intent) (int, map[string]any, map[string]string, error) {
	tableName := intent.TargetTable
	log.Printf("[proxy] Adding columns to table %s via LLM", tableName)

	analyzer := NewIntentAnalyzer(pe.engine.Manifest())
	prompt := analyzer.BuildSmartPrompt(method, path, body, nil)

	result, err := pe.engine.ApplyAutoApprove(ctx, prompt)
	if err != nil {
		return 500, map[string]any{
			"error":  "failed to add columns",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Added columns to %s via LLM (%d changes)", tableName, len(result.Changes))
	return retryResponse()
}

// handleRelationshipRoute adds a route for a relationship like /products/:id/orders.
func (pe *ProxyEngine) handleRelationshipRoute(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, intent *Intent) (int, map[string]any, map[string]string, error) {
	log.Printf("[proxy] Adding relationship route %s %s (%s -> %s)", method, path, intent.ParentTable, intent.ChildTable)

	currentManifest := pe.engine.Manifest()
	newManifest := copyManifest(currentManifest)

	// Build a query script for the relationship
	parentFK := intent.ParentTable + "_id"
	scriptName := fmt.Sprintf("%s_by_%s", intent.ChildTable, intent.ParentTable)
	scriptCode := fmt.Sprintf(`parent_id := request.param("id")
results := db.query("SELECT * FROM %s WHERE %s = ? AND deleted_at IS NULL", [parent_id])
response.json(results)`, intent.ChildTable, parentFK)

	route := manifest.Route{
		Path:        path,
		Method:      method,
		Description: fmt.Sprintf("Get %s for a specific %s", intent.ChildTable, intent.ParentTable),
		Script:      scriptName,
		ResponseType: "array",
	}
	script := manifest.Script{
		Name: scriptName,
		Code: scriptCode,
	}

	newManifest.Routes = append(newManifest.Routes, route)
	newManifest.Scripts = append(newManifest.Scripts, script)

	prompt := fmt.Sprintf("Add relationship route %s %s (%s -> %s)", method, path, intent.ParentTable, intent.ChildTable)
	result, err := pe.engine.ApplyManifestDirect(ctx, prompt, newManifest)
	if err != nil {
		return 500, map[string]any{
			"error":  "failed to add relationship route",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Added relationship route (%d changes)", len(result.Changes))
	return retryResponse()
}

// handleAI falls through to the LLM for ambiguous requests.
// It sends the full schema context so the AI can make smart decisions.
func (pe *ProxyEngine) handleAI(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, intent *Intent) (int, map[string]any, map[string]string, error) {
	log.Printf("[proxy] AI mode for %s %s: %s", method, path, intent.Reason)

	result, err := pe.engine.ApplyAutoApprove(ctx, intent.Prompt)
	if err != nil {
		log.Printf("[proxy] AI generation failed: %v", err)
		return 500, map[string]any{
			"error":  "AI generation failed",
			"detail": err.Error(),
			"method": method,
			"path":   path,
		}, nil, nil
	}

	log.Printf("[proxy] AI generated %s %s (%d changes)", method, path, len(result.Changes))
	return retryResponse()
}

// retryResponse returns a sentinel response that tells the handler to retry
// the request against the newly registered route.
func retryResponse() (int, map[string]any, map[string]string, error) {
	return 0, map[string]any{
		"__vibeserve_retry__": true,
	}, map[string]string{
		"X-VibeServe-Generated": "true",
	}, nil
}

// copyManifest creates a deep copy of the manifest so we can modify it
// without affecting the current state.
func copyManifest(m *manifest.Manifest) *manifest.Manifest {
	if m == nil {
		return &manifest.Manifest{
			Version: "1.0",
			Schemas: []manifest.Schema{},
			Routes:  []manifest.Route{},
			Scripts: []manifest.Script{},
			Seeds:   []manifest.Seed{},
		}
	}
	data, _ := json.Marshal(m)
	var copy manifest.Manifest
	json.Unmarshal(data, &copy)
	return &copy
}

// generateCRUD creates standard CRUD routes and scripts for a table.
func generateCRUD(tableName, resourcePath, scriptPrefix string) ([]manifest.Route, []manifest.Script) {
	singular := singularize(tableName)

	routes := []manifest.Route{
		{Path: resourcePath, Method: "GET", Description: fmt.Sprintf("List all %s", tableName), Script: "list_" + tableName, ResponseType: "array"},
		{Path: resourcePath + "/:id", Method: "GET", Description: fmt.Sprintf("Get a %s by ID", singular), Script: "get_" + singular, ResponseType: "object"},
		{Path: resourcePath, Method: "POST", Description: fmt.Sprintf("Create a %s", singular), Script: "create_" + singular, ResponseType: "object"},
		{Path: resourcePath + "/:id", Method: "PUT", Description: fmt.Sprintf("Update a %s", singular), Script: "update_" + singular, ResponseType: "object"},
		{Path: resourcePath + "/:id", Method: "DELETE", Description: fmt.Sprintf("Delete a %s", singular), Script: "delete_" + singular, ResponseType: "object"},
	}

	scripts := []manifest.Script{
		{Name: "list_" + tableName, Code: fmt.Sprintf("result := db.query(\"SELECT * FROM %s WHERE deleted_at IS NULL\", [])\nresponse.json(result)", tableName)},
		{Name: "get_" + singular, Code: fmt.Sprintf("id := request.param(\"id\")\nresult := db.query_one(\"SELECT * FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif result == undefined {\n  response.fail(404, \"%s not found\")\n} else {\n  response.json(result)\n}", tableName, singular)},
		{Name: "create_" + singular, Code: fmt.Sprintf("body := request.body()\nresult := db.insert(\"%s\", body)\nresponse.json(result, 201)", tableName)},
		{Name: "update_" + singular, Code: fmt.Sprintf("id := request.param(\"id\")\nbody := request.body()\nresult := db.update(\"%s\", id, body)\nif result == undefined {\n  response.fail(404, \"%s not found\")\n} else {\n  response.json(result)\n}", tableName, singular)},
		{Name: "delete_" + singular, Code: fmt.Sprintf("id := request.param(\"id\")\nexisting := db.query_one(\"SELECT id FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif existing == undefined {\n  response.fail(404, \"%s not found\")\n} else {\n  db.query(\"UPDATE %s SET deleted_at = date.now() WHERE id = ?\", [id])\n  response.json({\"deleted\": true})\n}", tableName, singular, tableName)},
	}

	return routes, scripts
}

// generateCustomRoute creates a route+script for the specific method+path+table combo.
func generateCustomRoute(method, path, tableName string, body map[string]any) (manifest.Route, manifest.Script) {
	// Sanitize path for script name
	safeName := strings.ReplaceAll(strings.Trim(path, "/"), "/", "_")
	safeName = strings.ReplaceAll(safeName, ":", "")
	safeName = strings.ReplaceAll(safeName, "-", "_")
	safeName = strings.ToLower(method) + "_" + safeName

	desc := fmt.Sprintf("%s %s", method, path)
	scriptCode := ""

	switch method {
	case "GET":
		if strings.Contains(path, ":") {
			// GET with ID param
			scriptCode = fmt.Sprintf("id := request.param(\"id\")\nresult := db.query_one(\"SELECT * FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif result == undefined {\n  response.fail(404, \"not found\")\n} else {\n  response.json(result)\n}", tableName)
		} else {
			scriptCode = fmt.Sprintf("result := db.query(\"SELECT * FROM %s WHERE deleted_at IS NULL\", [])\nresponse.json(result)", tableName)
		}
	case "POST":
		scriptCode = fmt.Sprintf("body := request.body()\nresult := db.insert(\"%s\", body)\nresponse.json(result, 201)", tableName)
	case "PUT", "PATCH":
		scriptCode = fmt.Sprintf("id := request.param(\"id\")\nbody := request.body()\nresult := db.update(\"%s\", id, body)\nif result == undefined {\n  response.fail(404, \"not found\")\n} else {\n  response.json(result)\n}", tableName)
	case "DELETE":
		scriptCode = fmt.Sprintf("id := request.param(\"id\")\nexisting := db.query_one(\"SELECT id FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif existing == undefined {\n  response.fail(404, \"not found\")\n} else {\n  db.query(\"UPDATE %s SET deleted_at = date.now() WHERE id = ?\", [id])\n  response.json({\"deleted\": true})\n}", tableName, tableName)
	default:
		scriptCode = fmt.Sprintf("result := db.query(\"SELECT * FROM %s WHERE deleted_at IS NULL\", [])\nresponse.json(result)", tableName)
	}

	return manifest.Route{
		Path:         path,
		Method:       method,
		Description:  desc,
		Script:       safeName,
		ResponseType: "object",
	}, manifest.Script{
		Name: safeName,
		Code: scriptCode,
	}
}

// routeExists checks if a route already exists in the list.
func routeExists(routes []manifest.Route, method, path string) bool {
	for _, r := range routes {
		if r.Method == method && r.Path == path {
			return true
		}
	}
	return false
}
