package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"sync"

	"github.com/vibeserve/vibeserve/internal/manifest"
)

// ProxyEngine intercepts unmatched HTTP requests and intelligently generates
// API endpoints. It uses a 3-phase approach:
//
//  1. Analyze intent — what does the user want? (deterministic, no AI)
//  2. Check existing schema — can we map to an existing table?
//  3. Generate — fast-path for obvious cases, AI for ambiguous ones
//
// This builds up a coherent database over time. Tables get linked via foreign
// keys, columns evolve as new fields appear, and relationship routes are
// detected automatically.
type ProxyEngine struct {
	engine *Engine

	// mu protects pending to prevent duplicate route generation for concurrent requests.
	mu      sync.Mutex
	pending map[string]chan proxyResult // key: "METHOD /path"
}

// proxyResult carries the outcome of a proxy generation attempt.
type proxyResult struct {
	StatusCode int
	Body       map[string]any
	Headers    map[string]string
	Err        error
}

// NewProxyEngine creates a new ProxyEngine backed by the given Engine.
func NewProxyEngine(eng *Engine) *ProxyEngine {
	return &ProxyEngine{
		engine:  eng,
		pending: make(map[string]chan proxyResult),
	}
}

// HandleUnknownRequest is called when a request hits an unmatched route.
// It analyzes the request intent, generates the appropriate API changes,
// and returns a response.
func (pe *ProxyEngine) HandleUnknownRequest(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, headers map[string]string) (int, map[string]any, map[string]string, error) {
	key := method + " " + path

	// Check if this route is already being generated by another goroutine.
	pe.mu.Lock()
	if ch, ok := pe.pending[key]; ok {
		pe.mu.Unlock()
		result := <-ch
		return result.StatusCode, result.Body, result.Headers, result.Err
	}

	// Mark this route as being generated.
	ch := make(chan proxyResult, 1)
	pe.pending[key] = ch
	pe.mu.Unlock()

	// Generate the route.
	status, respBody, respHeaders, err := pe.smartGenerate(ctx, method, path, body, queryParams)

	result := proxyResult{
		StatusCode: status,
		Body:       respBody,
		Headers:    respHeaders,
		Err:        err,
	}

	pe.mu.Lock()
	delete(pe.pending, key)
	pe.mu.Unlock()

	ch <- result
	return status, respBody, respHeaders, err
}

// smartGenerate is the core of the intent-aware proxy.
// Phase 1: Analyze intent (deterministic, instant)
// Phase 2: Execute based on intent type
func (pe *ProxyEngine) smartGenerate(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string) (int, map[string]any, map[string]string, error) {
	currentManifest := pe.engine.Manifest()

	// Phase 1: Analyze intent
	analyzer := NewIntentAnalyzer(currentManifest)
	intent := analyzer.Analyze(method, path, body, queryParams)

	log.Printf("[proxy] Intent: %s for %s %s (resource=%s)", intent.Type, method, path, intent.Resource)

	switch intent.Type {
	case IntentCreateTable:
		return pe.handleCreateTable(ctx, method, path, body, intent)

	case IntentAddRoute:
		return pe.handleAddRoute(ctx, method, path, body, intent)

	case IntentAddColumn:
		return pe.handleAddColumn(ctx, method, path, body, intent)

	case IntentAddRelationshipRoute:
		return pe.handleRelationshipRoute(ctx, method, path, body, queryParams, intent)

	case IntentAI:
		return pe.handleAI(ctx, method, path, body, queryParams, intent)

	default:
		return 500, map[string]any{"error": "unknown intent type"}, nil, nil
	}
}

// handleCreateTable deterministically creates a new table + CRUD routes.
// No AI needed — everything comes from the intent analysis.
func (pe *ProxyEngine) handleCreateTable(ctx context.Context, method, path string, body map[string]any, intent *Intent) (int, map[string]any, map[string]string, error) {
	tableName := intent.TableName
	log.Printf("[proxy] Creating table %s with %d columns", tableName, len(intent.Columns))

	// Build the new manifest by extending the current one
	currentManifest := pe.engine.Manifest()
	newManifest := copyManifest(currentManifest)

	// Add the new schema
	newManifest.Schemas = append(newManifest.Schemas, manifest.Schema{
		Table:   tableName,
		Columns: intent.Columns,
	})

	// Generate CRUD routes and scripts for the new table
	resourcePath := "/" + tableName
	singular := singularize(tableName)
	scriptPrefix := singular

	routes, scripts := generateCRUD(tableName, resourcePath, scriptPrefix)
	newManifest.Routes = append(newManifest.Routes, routes...)
	newManifest.Scripts = append(newManifest.Scripts, scripts...)

	// Also add the custom route that triggered this (if different from CRUD)
	if intent.ParentTable != "" {
		// Relationship path — generate a filtered query route
		fkCol := singularize(intent.ParentTable) + "_id"
		scriptName := fmt.Sprintf("%s_by_%s", intent.TableName, singularize(intent.ParentTable))
		scriptCode := fmt.Sprintf("parent_id := request.param(\"id\")\nresults := db.query(\"SELECT * FROM %s WHERE %s = ? AND deleted_at IS NULL\", [parent_id])\nresponse.json(results)", intent.TableName, fkCol)

		customRoute := manifest.Route{
			Path:         path,
			Method:       method,
			Description:  fmt.Sprintf("Get %s for a specific %s", intent.TableName, singularize(intent.ParentTable)),
			Script:       scriptName,
			ResponseType: "array",
		}
		customScript := manifest.Script{
			Name: scriptName,
			Code: scriptCode,
		}

		if !routeExists(newManifest.Routes, method, path) {
			newManifest.Routes = append(newManifest.Routes, customRoute)
			newManifest.Scripts = append(newManifest.Scripts, customScript)
		}
	} else {
		// Regular custom route
		customRoute, customScript := generateCustomRoute(method, path, tableName, body)
		if !routeExists(newManifest.Routes, method, path) {
			newManifest.Routes = append(newManifest.Routes, customRoute)
			newManifest.Scripts = append(newManifest.Scripts, customScript)
		}
	}

	// Apply
	prompt := fmt.Sprintf("Auto-create table %s from %s %s", tableName, method, path)
	result, err := pe.engine.ApplyManifestDirect(ctx, prompt, newManifest)
	if err != nil {
		log.Printf("[proxy] Failed to create table %s: %v", tableName, err)
		return 500, map[string]any{
			"error":  "failed to create table",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Created table %s (%d changes)", tableName, len(result.Changes))
	return retryResponse()
}

// handleAddRoute maps a new path to an existing table. No schema changes needed.
func (pe *ProxyEngine) handleAddRoute(ctx context.Context, method, path string, body map[string]any, intent *Intent) (int, map[string]any, map[string]string, error) {
	tableName := intent.TargetTable
	log.Printf("[proxy] Adding route %s %s -> existing table %s", method, path, tableName)

	currentManifest := pe.engine.Manifest()
	newManifest := copyManifest(currentManifest)

	// Add the custom route pointing to the existing table
	route, script := generateCustomRoute(method, path, tableName, body)
	newManifest.Routes = append(newManifest.Routes, route)
	newManifest.Scripts = append(newManifest.Scripts, script)

	prompt := fmt.Sprintf("Add route %s %s mapping to table %s", method, path, tableName)
	result, err := pe.engine.ApplyManifestDirect(ctx, prompt, newManifest)
	if err != nil {
		return 500, map[string]any{
			"error":  "failed to add route",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Added route %s %s (%d changes)", method, path, len(result.Changes))
	return retryResponse()
}

// handleAddColumn adds new columns to an existing table, then adds the route.
func (pe *ProxyEngine) handleAddColumn(ctx context.Context, method, path string, body map[string]any, intent *Intent) (int, map[string]any, map[string]string, error) {
	tableName := intent.TargetTable
	log.Printf("[proxy] Adding %d columns to table %s", len(intent.ColumnsToAdd), tableName)

	currentManifest := pe.engine.Manifest()
	newManifest := copyManifest(currentManifest)

	// Add columns to the existing schema
	for i := range newManifest.Schemas {
		if strings.EqualFold(newManifest.Schemas[i].Table, tableName) {
			newManifest.Schemas[i].Columns = append(newManifest.Schemas[i].Columns, intent.ColumnsToAdd...)
			break
		}
	}

	// Add the custom route
	route, script := generateCustomRoute(method, path, tableName, body)
	newManifest.Routes = append(newManifest.Routes, route)
	newManifest.Scripts = append(newManifest.Scripts, script)

	prompt := fmt.Sprintf("Add columns to %s from %s %s", tableName, method, path)
	result, err := pe.engine.ApplyManifestDirect(ctx, prompt, newManifest)
	if err != nil {
		return 500, map[string]any{
			"error":  "failed to add columns",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Added columns to %s (%d changes)", tableName, len(result.Changes))
	return retryResponse()
}

// handleRelationshipRoute adds a route for a relationship like /products/:id/orders.
func (pe *ProxyEngine) handleRelationshipRoute(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, intent *Intent) (int, map[string]any, map[string]string, error) {
	log.Printf("[proxy] Adding relationship route %s %s (%s -> %s)", method, path, intent.ParentTable, intent.ChildTable)

	currentManifest := pe.engine.Manifest()
	newManifest := copyManifest(currentManifest)

	// Build a query script for the relationship
	parentFK := intent.ParentTable + "_id"
	scriptName := fmt.Sprintf("%s_by_%s", intent.ChildTable, intent.ParentTable)
	scriptCode := fmt.Sprintf(`parent_id := request.param("id")
results := db.query("SELECT * FROM %s WHERE %s = ? AND deleted_at IS NULL", [parent_id])
response.json(results)`, intent.ChildTable, parentFK)

	route := manifest.Route{
		Path:        path,
		Method:      method,
		Description: fmt.Sprintf("Get %s for a specific %s", intent.ChildTable, intent.ParentTable),
		Script:      scriptName,
		ResponseType: "array",
	}
	script := manifest.Script{
		Name: scriptName,
		Code: scriptCode,
	}

	newManifest.Routes = append(newManifest.Routes, route)
	newManifest.Scripts = append(newManifest.Scripts, script)

	prompt := fmt.Sprintf("Add relationship route %s %s (%s -> %s)", method, path, intent.ParentTable, intent.ChildTable)
	result, err := pe.engine.ApplyManifestDirect(ctx, prompt, newManifest)
	if err != nil {
		return 500, map[string]any{
			"error":  "failed to add relationship route",
			"detail": err.Error(),
		}, nil, nil
	}

	log.Printf("[proxy] Added relationship route (%d changes)", len(result.Changes))
	return retryResponse()
}

// handleAI falls through to the LLM for ambiguous requests.
// It sends the full schema context so the AI can make smart decisions.
func (pe *ProxyEngine) handleAI(ctx context.Context, method, path string, body map[string]any, queryParams map[string]string, intent *Intent) (int, map[string]any, map[string]string, error) {
	log.Printf("[proxy] AI mode for %s %s: %s", method, path, intent.Reason)

	result, err := pe.engine.ApplyAutoApprove(ctx, intent.Prompt)
	if err != nil {
		log.Printf("[proxy] AI generation failed: %v", err)
		return 500, map[string]any{
			"error":  "AI generation failed",
			"detail": err.Error(),
			"method": method,
			"path":   path,
		}, nil, nil
	}

	log.Printf("[proxy] AI generated %s %s (%d changes)", method, path, len(result.Changes))
	return retryResponse()
}

// retryResponse returns a sentinel response that tells the handler to retry
// the request against the newly registered route.
func retryResponse() (int, map[string]any, map[string]string, error) {
	return 0, map[string]any{
		"__vibeserve_retry__": true,
	}, map[string]string{
		"X-VibeServe-Generated": "true",
	}, nil
}

// copyManifest creates a deep copy of the manifest so we can modify it
// without affecting the current state.
func copyManifest(m *manifest.Manifest) *manifest.Manifest {
	if m == nil {
		return &manifest.Manifest{
			Version: "1.0",
			Schemas: []manifest.Schema{},
			Routes:  []manifest.Route{},
			Scripts: []manifest.Script{},
			Seeds:   []manifest.Seed{},
		}
	}
	data, _ := json.Marshal(m)
	var copy manifest.Manifest
	json.Unmarshal(data, &copy)
	return &copy
}

// generateCRUD creates standard CRUD routes and scripts for a table.
func generateCRUD(tableName, resourcePath, scriptPrefix string) ([]manifest.Route, []manifest.Script) {
	singular := singularize(tableName)

	routes := []manifest.Route{
		{Path: resourcePath, Method: "GET", Description: fmt.Sprintf("List all %s", tableName), Script: "list_" + tableName, ResponseType: "array"},
		{Path: resourcePath + "/:id", Method: "GET", Description: fmt.Sprintf("Get a %s by ID", singular), Script: "get_" + singular, ResponseType: "object"},
		{Path: resourcePath, Method: "POST", Description: fmt.Sprintf("Create a %s", singular), Script: "create_" + singular, ResponseType: "object"},
		{Path: resourcePath + "/:id", Method: "PUT", Description: fmt.Sprintf("Update a %s", singular), Script: "update_" + singular, ResponseType: "object"},
		{Path: resourcePath + "/:id", Method: "DELETE", Description: fmt.Sprintf("Delete a %s", singular), Script: "delete_" + singular, ResponseType: "object"},
	}

	scripts := []manifest.Script{
		{Name: "list_" + tableName, Code: fmt.Sprintf("result := db.query(\"SELECT * FROM %s WHERE deleted_at IS NULL\", [])\nresponse.json(result)", tableName)},
		{Name: "get_" + singular, Code: fmt.Sprintf("id := request.param(\"id\")\nresult := db.query_one(\"SELECT * FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif result == undefined {\n  response.fail(404, \"%s not found\")\n} else {\n  response.json(result)\n}", tableName, singular)},
		{Name: "create_" + singular, Code: fmt.Sprintf("body := request.body()\nresult := db.insert(\"%s\", body)\nresponse.json(result, 201)", tableName)},
		{Name: "update_" + singular, Code: fmt.Sprintf("id := request.param(\"id\")\nbody := request.body()\nresult := db.update(\"%s\", id, body)\nif result == undefined {\n  response.fail(404, \"%s not found\")\n} else {\n  response.json(result)\n}", tableName, singular)},
		{Name: "delete_" + singular, Code: fmt.Sprintf("id := request.param(\"id\")\nexisting := db.query_one(\"SELECT id FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif existing == undefined {\n  response.fail(404, \"%s not found\")\n} else {\n  db.query(\"UPDATE %s SET deleted_at = date.now() WHERE id = ?\", [id])\n  response.json({\"deleted\": true})\n}", tableName, singular, tableName)},
	}

	return routes, scripts
}

// generateCustomRoute creates a route+script for the specific method+path+table combo.
func generateCustomRoute(method, path, tableName string, body map[string]any) (manifest.Route, manifest.Script) {
	// Sanitize path for script name
	safeName := strings.ReplaceAll(strings.Trim(path, "/"), "/", "_")
	safeName = strings.ReplaceAll(safeName, ":", "")
	safeName = strings.ReplaceAll(safeName, "-", "_")
	safeName = strings.ToLower(method) + "_" + safeName

	desc := fmt.Sprintf("%s %s", method, path)
	scriptCode := ""

	switch method {
	case "GET":
		if strings.Contains(path, ":") {
			// GET with ID param
			scriptCode = fmt.Sprintf("id := request.param(\"id\")\nresult := db.query_one(\"SELECT * FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif result == undefined {\n  response.fail(404, \"not found\")\n} else {\n  response.json(result)\n}", tableName)
		} else {
			scriptCode = fmt.Sprintf("result := db.query(\"SELECT * FROM %s WHERE deleted_at IS NULL\", [])\nresponse.json(result)", tableName)
		}
	case "POST":
		scriptCode = fmt.Sprintf("body := request.body()\nresult := db.insert(\"%s\", body)\nresponse.json(result, 201)", tableName)
	case "PUT", "PATCH":
		scriptCode = fmt.Sprintf("id := request.param(\"id\")\nbody := request.body()\nresult := db.update(\"%s\", id, body)\nif result == undefined {\n  response.fail(404, \"not found\")\n} else {\n  response.json(result)\n}", tableName)
	case "DELETE":
		scriptCode = fmt.Sprintf("id := request.param(\"id\")\nexisting := db.query_one(\"SELECT id FROM %s WHERE id = ? AND deleted_at IS NULL\", [id])\nif existing == undefined {\n  response.fail(404, \"not found\")\n} else {\n  db.query(\"UPDATE %s SET deleted_at = date.now() WHERE id = ?\", [id])\n  response.json({\"deleted\": true})\n}", tableName, tableName)
	default:
		scriptCode = fmt.Sprintf("result := db.query(\"SELECT * FROM %s WHERE deleted_at IS NULL\", [])\nresponse.json(result)", tableName)
	}

	return manifest.Route{
		Path:         path,
		Method:       method,
		Description:  desc,
		Script:       safeName,
		ResponseType: "object",
	}, manifest.Script{
		Name: safeName,
		Code: scriptCode,
	}
}

// routeExists checks if a route already exists in the list.
func routeExists(routes []manifest.Route, method, path string) bool {
	for _, r := range routes {
		if r.Method == method && r.Path == path {
			return true
		}
	}
	return false
}
