package watch

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/vibeserve/vibeserve/internal/export"
	"github.com/vibeserve/vibeserve/internal/manifest"
)

// Config holds watch mode configuration.
type Config struct {
	ManifestPath string // path to manifest.json (default: .vibe/manifest.json)
	ExportDir    string // path to exported project
	Format       string // export format: go, express, next
	DBType       string // database type: sqlite, postgres
	TypeScript   bool   // generate TypeScript types
	PollInterval time.Duration
}

// Watcher monitors the manifest and re-exports on change.
type Watcher struct {
	cfg          Config
	lastModTime  time.Time
	lastManifest *manifest.Manifest
	migrationSeq int
}

// New creates a Watcher.
func New(cfg Config) *Watcher {
	if cfg.PollInterval == 0 {
		cfg.PollInterval = time.Second
	}
	if cfg.Format == "" {
		cfg.Format = "express"
	}
	if cfg.DBType == "" {
		cfg.DBType = "sqlite"
	}
	return &Watcher{cfg: cfg}
}

// Start begins watching. Call in a goroutine — blocks until stop is called.
// onChange is called with a summary when the manifest changes.
func (w *Watcher) Start(stop <-chan struct{}, onChange func(summary string)) {
	// Load initial manifest
	m, modTime, err := w.loadManifest()
	if err != nil {
		log.Printf("[watch] initial load failed: %v", err)
	} else {
		w.lastManifest = m
		w.lastModTime = modTime
		w.migrationSeq = countExistingMigrations(w.cfg.ExportDir)
		log.Printf("[watch] watching %s (format: %s, export: %s)", w.cfg.ManifestPath, w.cfg.Format, w.cfg.ExportDir)
	}

	ticker := time.NewTicker(w.cfg.PollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-stop:
			return
		case <-ticker.C:
			w.check(onChange)
		}
	}
}

func (w *Watcher) check(onChange func(string)) {
	info, err := os.Stat(w.cfg.ManifestPath)
	if err != nil {
		return // file doesn't exist yet
	}

	modTime := info.ModTime()
	if !modTime.After(w.lastModTime) {
		return // no change
	}
	w.lastModTime = modTime

	newManifest, _, err := w.loadManifest()
	if err != nil {
		log.Printf("[watch] reload failed: %v", err)
		return
	}

	// Diff
	var summary string
	if w.lastManifest != nil {
		changes := manifest.Diff(w.lastManifest, newManifest)
		if len(changes) == 0 {
			return // file touched but content unchanged
		}
		summary = formatChanges(changes)

		// Generate migration for PostgreSQL
		if w.cfg.DBType == "postgres" {
			w.migrationSeq++
			migrationPath := w.generateMigration(changes, w.migrationSeq)
			if migrationPath != "" {
				summary += fmt.Sprintf("\n  Migration: %s", migrationPath)
			}
		}
	} else {
		summary = fmt.Sprintf("Initial load: %d tables, %d routes", len(newManifest.Schemas), len(newManifest.Routes))
	}

	// Re-export
	if err := w.reexport(newManifest); err != nil {
		log.Printf("[watch] re-export failed: %v", err)
		summary += fmt.Sprintf("\n  Export error: %v", err)
	} else {
		summary += fmt.Sprintf("\n  Re-exported to %s", w.cfg.ExportDir)
	}

	w.lastManifest = newManifest

	if onChange != nil {
		onChange(summary)
	}
}

func (w *Watcher) loadManifest() (*manifest.Manifest, time.Time, error) {
	info, err := os.Stat(w.cfg.ManifestPath)
	if err != nil {
		return nil, time.Time{}, err
	}
	m, err := manifest.LoadFromFile(w.cfg.ManifestPath)
	if err != nil {
		return nil, time.Time{}, err
	}
	return m, info.ModTime(), nil
}

func (w *Watcher) reexport(m *manifest.Manifest) error {
	// Remove and recreate export dir
	os.RemoveAll(w.cfg.ExportDir)

	exp := export.NewExporter(m, w.cfg.ExportDir)
	exp.SetVibeDir(filepath.Dir(w.cfg.ManifestPath))
	if w.cfg.DBType != "" {
		exp.SetDBType(w.cfg.DBType)
	}
	if w.cfg.TypeScript {
		exp.SetTypeScript(true)
	}

	switch w.cfg.Format {
	case "next":
		return exp.RunNext()
	case "express":
		return exp.RunExpress()
	default:
		return exp.Run()
	}
}

func (w *Watcher) generateMigration(changes []manifest.Change, seq int) string {
	sql := GenerateMigrationSQL(changes)
	if sql == "" {
		return ""
	}

	migrationsDir := filepath.Join(w.cfg.ExportDir, "migrations")
	os.MkdirAll(migrationsDir, 0o755)

	// Build a short description from the first change
	desc := "update"
	if len(changes) > 0 {
		desc = sanitizeFilename(changes[0].Detail)
	}

	filename := fmt.Sprintf("%03d_%s.sql", seq, desc)
	path := filepath.Join(migrationsDir, filename)

	header := fmt.Sprintf("-- Migration %03d\n-- Generated by vibeserve watch\n-- %s\n\n", seq, time.Now().Format(time.RFC3339))
	os.WriteFile(path, []byte(header+sql), 0o644)

	return filepath.Join("migrations", filename)
}

func formatChanges(changes []manifest.Change) string {
	tables, cols, routes := 0, 0, 0
	for _, c := range changes {
		switch c.Type {
		case manifest.ChangeAddTable:
			tables++
		case manifest.ChangeAddColumn:
			cols++
		case manifest.ChangeAddRoute, manifest.ChangeUpdateRoute, manifest.ChangeRemoveRoute:
			routes++
		}
	}

	parts := []string{}
	if tables > 0 {
		parts = append(parts, fmt.Sprintf("+%d tables", tables))
	}
	if cols > 0 {
		parts = append(parts, fmt.Sprintf("+%d columns", cols))
	}
	if routes > 0 {
		parts = append(parts, fmt.Sprintf("%d route changes", routes))
	}

	result := "  Changes: "
	if len(parts) > 0 {
		for i, p := range parts {
			if i > 0 {
				result += ", "
			}
			result += p
		}
	} else {
		result += fmt.Sprintf("%d changes", len(changes))
	}
	return result
}

func countExistingMigrations(exportDir string) int {
	migrationsDir := filepath.Join(exportDir, "migrations")
	entries, err := os.ReadDir(migrationsDir)
	if err != nil {
		return 0
	}
	count := 0
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".sql" {
			count++
		}
	}
	return count
}

func sanitizeFilename(s string) string {
	// Take first 40 chars, replace non-alphanumeric with underscore
	if len(s) > 40 {
		s = s[:40]
	}
	result := make([]byte, 0, len(s))
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_' {
			result = append(result, byte(c))
		} else if c >= 'A' && c <= 'Z' {
			result = append(result, byte(c-'A'+'a'))
		} else if c == ' ' || c == '-' {
			result = append(result, '_')
		}
	}
	if len(result) == 0 {
		return "update"
	}
	return string(result)
}
