package export

import (
	"fmt"
	"strings"

	"github.com/vibeserve/vibeserve/internal/manifest"
)

// sqliteToPostgresType maps a manifest Column's SQLite type to the
// corresponding PostgreSQL type.
func sqliteToPostgresType(col manifest.Column) string {
	if col.Primary && col.Auto {
		return "SERIAL"
	}
	switch col.Type {
	case "INTEGER":
		return "INTEGER"
	case "TEXT":
		return "TEXT"
	case "REAL":
		return "DOUBLE PRECISION"
	case "BOOLEAN":
		return "BOOLEAN"
	case "DATE":
		return "DATE"
	case "DATETIME":
		return "TIMESTAMP"
	default:
		return "TEXT"
	}
}

// GeneratePostgresSchema generates a PostgreSQL schema.sql file from the
// given manifest schemas.
func GeneratePostgresSchema(schemas []manifest.Schema) string {
	var b strings.Builder

	b.WriteString("-- Generated by vibeserve export\n\n")

	for i, schema := range schemas {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", schema.Table))

		for j, col := range schema.Columns {
			b.WriteString("  ")
			b.WriteString(col.Name)
			b.WriteString(" ")
			b.WriteString(sqliteToPostgresType(col))

			if col.Primary {
				b.WriteString(" PRIMARY KEY")
			}

			// NOT NULL for required columns, but not on PRIMARY KEY columns
			// (NOT NULL is implicit for PKs).
			if col.Required && !col.Primary {
				b.WriteString(" NOT NULL")
			}

			if col.Unique {
				b.WriteString(" UNIQUE")
			}

			if col.Default != nil {
				b.WriteString(" DEFAULT ")
				switch d := col.Default.(type) {
				case string:
					// SQL expressions (containing parentheses) are emitted raw.
					if strings.Contains(d, "(") {
						b.WriteString(d)
					} else {
						escaped := strings.ReplaceAll(d, "'", "''")
						b.WriteString(fmt.Sprintf("'%s'", escaped))
					}
				case bool:
					b.WriteString(fmt.Sprintf("%t", d))
				case float64:
					if d == float64(int64(d)) {
						b.WriteString(fmt.Sprintf("%d", int64(d)))
					} else {
						b.WriteString(fmt.Sprintf("%g", d))
					}
				default:
					b.WriteString(fmt.Sprintf("'%v'", d))
				}
			}

			if col.References != "" {
				b.WriteString(fmt.Sprintf(" REFERENCES %s", col.References))
			}

			if j < len(schema.Columns)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}

		b.WriteString(");\n")
	}

	return b.String()
}

// GeneratePostgresSeed generates a PostgreSQL seed.sql file wrapped in a
// BEGIN/COMMIT transaction block.
func GeneratePostgresSeed(seeds []manifest.Seed, schemas []manifest.Schema) string {
	if len(seeds) == 0 {
		return "-- No seed data.\n"
	}

	// Build schema lookup for column ordering and auto-increment detection.
	schemaMap := make(map[string]manifest.Schema, len(schemas))
	for _, s := range schemas {
		schemaMap[s.Table] = s
	}

	var b strings.Builder

	b.WriteString("-- Generated by vibeserve export\n\n")
	b.WriteString("BEGIN;\n\n")

	for _, seed := range seeds {
		schema, hasSchema := schemaMap[seed.Table]

		for _, row := range seed.Rows {
			var cols []string
			var vals []string

			if hasSchema {
				// Use schema column order for consistent INSERT ordering.
				for _, col := range schema.Columns {
					if v, ok := row[col.Name]; ok {
						cols = append(cols, col.Name)
						vals = append(vals, formatPostgresValue(v))
					}
				}
			} else {
				// Fallback: alphabetical order from row keys.
				for k, v := range row {
					cols = append(cols, k)
					vals = append(vals, formatPostgresValue(v))
				}
			}

			b.WriteString(fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s);\n",
				seed.Table,
				strings.Join(cols, ", "),
				strings.Join(vals, ", "),
			))
		}

		// Reset sequence for tables with auto-increment PK.
		if hasSchema {
			for _, col := range schema.Columns {
				if col.Primary && col.Auto {
					pkCol := findPKColumn(schema)
					b.WriteString(fmt.Sprintf(
						"SELECT setval(pg_get_serial_sequence('%s', '%s'), COALESCE(MAX(%s), 0) + 1, false) FROM %s;\n",
						seed.Table, pkCol, pkCol, seed.Table,
					))
					break
				}
			}
		}

		b.WriteString("\n")
	}

	b.WriteString("COMMIT;\n")

	return b.String()
}

// formatPostgresValue formats a Go value as a PostgreSQL literal.
func formatPostgresValue(v any) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case string:
		escaped := strings.ReplaceAll(val, "'", "''")
		return fmt.Sprintf("'%s'", escaped)
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case bool:
		return fmt.Sprintf("%t", val)
	default:
		return fmt.Sprintf("'%v'", v)
	}
}
