package export

import (
	"fmt"
	"strings"

	"github.com/vibeserve/vibeserve/internal/manifest"
)

// tsType maps a manifest column type to a TypeScript type.
func tsType(col manifest.Column) string {
	switch col.Type {
	case "INTEGER":
		return "number"
	case "REAL":
		return "number"
	case "BOOLEAN":
		return "boolean"
	case "TEXT", "DATE", "DATETIME":
		return "string"
	default:
		return "any"
	}
}

// GenerateTypeScript generates src/types.ts with interfaces for all schemas.
func GenerateTypeScript(schemas []manifest.Schema) string {
	// Inject timestamps
	injected := make([]manifest.Schema, len(schemas))
	for i, s := range schemas {
		injected[i] = manifest.InjectTimestamps(s)
	}
	schemas = injected

	var b strings.Builder
	b.WriteString("// Auto-generated by vibeserve export — do not edit manually.\n\n")

	// ListOptions — shared across all tables
	b.WriteString("export interface ListOptions {\n")
	b.WriteString("  limit?: number;\n")
	b.WriteString("  offset?: number;\n")
	b.WriteString("  sort?: string;\n")
	b.WriteString("  order?: 'asc' | 'desc';\n")
	b.WriteString("  search?: string;\n")
	b.WriteString("  [key: string]: any;\n")
	b.WriteString("}\n\n")

	for _, schema := range schemas {
		structName := TableToStructName(schema.Table)

		// Main interface — all columns
		b.WriteString(fmt.Sprintf("export interface %s {\n", structName))
		for _, col := range schema.Columns {
			ts := tsType(col)
			if col.Name == "deleted_at" {
				ts = "string | null"
			}
			b.WriteString(fmt.Sprintf("  %s: %s;\n", col.Name, ts))
		}
		b.WriteString("}\n\n")

		// CreateInput — excludes PK/auto and timestamp columns
		b.WriteString(fmt.Sprintf("export interface Create%sInput {\n", structName))
		for _, col := range schema.Columns {
			if col.Primary && col.Auto {
				continue
			}
			if col.Name == "created_at" || col.Name == "updated_at" || col.Name == "deleted_at" {
				continue
			}
			ts := tsType(col)
			optional := "?"
			if col.Required {
				optional = ""
			}
			b.WriteString(fmt.Sprintf("  %s%s: %s;\n", col.Name, optional, ts))
		}
		b.WriteString("}\n\n")

		// UpdateInput — all non-PK, non-timestamp columns optional
		b.WriteString(fmt.Sprintf("export interface Update%sInput {\n", structName))
		for _, col := range schema.Columns {
			if col.Primary {
				continue
			}
			if col.Name == "created_at" || col.Name == "updated_at" || col.Name == "deleted_at" {
				continue
			}
			ts := tsType(col)
			b.WriteString(fmt.Sprintf("  %s?: %s;\n", col.Name, ts))
		}
		b.WriteString("}\n\n")
	}

	return b.String()
}

// GenerateTSConfig generates a tsconfig.json.
func GenerateTSConfig() string {
	return `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": ".",
    "strict": false,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "declaration": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`
}
