package export

import (
	"fmt"
	"strings"

	"github.com/vibeserve/vibeserve/internal/manifest"
)

// sqliteToPostgresType maps a manifest Column's SQLite type to the
// corresponding PostgreSQL type.
func sqliteToPostgresType(col manifest.Column) string {
	if col.Primary && col.Auto {
		return "SERIAL"
	}
	switch col.Type {
	case "INTEGER":
		return "INTEGER"
	case "TEXT":
		return "TEXT"
	case "REAL":
		return "DOUBLE PRECISION"
	case "BOOLEAN":
		return "BOOLEAN"
	case "DATE":
		return "DATE"
	case "DATETIME":
		return "TIMESTAMP"
	default:
		return "TEXT"
	}
}

// GeneratePostgresSchema generates a PostgreSQL schema.sql file from the
// given manifest schemas.
func GeneratePostgresSchema(schemas []manifest.Schema) string {
	injected := make([]manifest.Schema, len(schemas))
	for i, s := range schemas {
		injected[i] = manifest.InjectTimestamps(s)
	}
	schemas = injected

	var b strings.Builder

	b.WriteString("-- Generated by vibeserve export\n\n")

	for i, schema := range schemas {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", schema.Table))

		for j, col := range schema.Columns {
			b.WriteString("  ")
			b.WriteString(col.Name)
			b.WriteString(" ")
			b.WriteString(sqliteToPostgresType(col))

			if col.Primary {
				b.WriteString(" PRIMARY KEY")
			}

			// NOT NULL for required columns, but not on PRIMARY KEY columns
			// (NOT NULL is implicit for PKs).
			if col.Required && !col.Primary {
				b.WriteString(" NOT NULL")
			}

			if col.Unique {
				b.WriteString(" UNIQUE")
			}

			if col.Default != nil {
				b.WriteString(" DEFAULT ")
				switch d := col.Default.(type) {
				case string:
					upper := strings.ToUpper(d)
					if upper == "NOW" || strings.Contains(d, "(") {
						if upper == "NOW" {
							b.WriteString("NOW()")
						} else {
							b.WriteString(d)
						}
					} else {
						escaped := strings.ReplaceAll(d, "'", "''")
						b.WriteString(fmt.Sprintf("'%s'", escaped))
					}
				case bool:
					b.WriteString(fmt.Sprintf("%t", d))
				case float64:
					if d == float64(int64(d)) {
						b.WriteString(fmt.Sprintf("%d", int64(d)))
					} else {
						b.WriteString(fmt.Sprintf("%g", d))
					}
				default:
					b.WriteString(fmt.Sprintf("'%v'", d))
				}
			}

			if col.References != "" {
				b.WriteString(fmt.Sprintf(" REFERENCES %s", col.References))
			}

			if j < len(schema.Columns)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}

		b.WriteString(");\n")
	}

	// Generate indexes for foreign key columns and deleted_at.
	hasIndexes := false
	for _, schema := range schemas {
		for _, col := range schema.Columns {
			if col.References != "" || col.Name == "deleted_at" {
				hasIndexes = true
				break
			}
		}
		if hasIndexes {
			break
		}
	}

	if hasIndexes {
		b.WriteString("\n-- Indexes\n")
		for _, schema := range schemas {
			for _, col := range schema.Columns {
				if col.References != "" {
					b.WriteString(fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_%s ON %s (%s);\n",
						schema.Table, col.Name, schema.Table, col.Name))
				}
				if col.Name == "deleted_at" {
					b.WriteString(fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_deleted_at ON %s (deleted_at);\n",
						schema.Table, schema.Table))
				}
			}
		}
	}

	return b.String()
}

// GeneratePostgresSeed generates a PostgreSQL seed.sql file wrapped in a
// BEGIN/COMMIT transaction block.
func GeneratePostgresSeed(seeds []manifest.Seed, schemas []manifest.Schema) string {
	if len(seeds) == 0 {
		return "-- No seed data.\n"
	}

	// Build schema lookup for column ordering and auto-increment detection.
	schemaMap := make(map[string]manifest.Schema, len(schemas))
	for _, s := range schemas {
		schemaMap[s.Table] = s
	}

	var b strings.Builder

	b.WriteString("-- Generated by vibeserve export\n\n")
	b.WriteString("BEGIN;\n\n")

	for _, seed := range seeds {
		schema, hasSchema := schemaMap[seed.Table]

		for _, row := range seed.Rows {
			var cols []string
			var vals []string

			if hasSchema {
				// Use schema column order for consistent INSERT ordering.
				for _, col := range schema.Columns {
					if v, ok := row[col.Name]; ok {
						cols = append(cols, col.Name)
						vals = append(vals, formatPostgresValue(v))
					}
				}
			} else {
				// Fallback: alphabetical order from row keys.
				for k, v := range row {
					cols = append(cols, k)
					vals = append(vals, formatPostgresValue(v))
				}
			}

			b.WriteString(fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s);\n",
				seed.Table,
				strings.Join(cols, ", "),
				strings.Join(vals, ", "),
			))
		}

		// Reset sequence for tables with auto-increment PK.
		if hasSchema {
			for _, col := range schema.Columns {
				if col.Primary && col.Auto {
					pkCol := findPKColumn(schema)
					b.WriteString(fmt.Sprintf(
						"SELECT setval(pg_get_serial_sequence('%s', '%s'), COALESCE(MAX(%s), 0) + 1, false) FROM %s;\n",
						seed.Table, pkCol, pkCol, seed.Table,
					))
					break
				}
			}
		}

		b.WriteString("\n")
	}

	b.WriteString("COMMIT;\n")

	return b.String()
}

// GeneratePostgresDatabaseJS generates a database.js file that uses the pg
// (node-postgres) package. It produces async CRUD helpers for each schema table.
func GeneratePostgresDatabaseJS(schemas []manifest.Schema) string {
	injected := make([]manifest.Schema, len(schemas))
	for i, s := range schemas {
		injected[i] = manifest.InjectTimestamps(s)
	}
	schemas = injected

	var b strings.Builder

	// Connection setup
	b.WriteString("const { Pool } = require('pg');\n\n")
	b.WriteString("const pool = new Pool({\n")
	b.WriteString("  connectionString: process.env.DATABASE_URL,\n")
	b.WriteString("});\n\n")

	// initDB — tests connection
	b.WriteString("async function initDB() {\n")
	b.WriteString("  const client = await pool.connect();\n")
	b.WriteString("  try {\n")
	b.WriteString("    await client.query('SELECT 1');\n")
	b.WriteString("    console.log('Database connected');\n")
	b.WriteString("  } finally {\n")
	b.WriteString("    client.release();\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// getDB — returns pool
	b.WriteString("function getDB() {\n")
	b.WriteString("  return pool;\n")
	b.WriteString("}\n\n")

	// Per-table CRUD helpers
	var exportNames []string
	exportNames = append(exportNames, "initDB", "getDB", "closeDB")

	for _, schema := range schemas {
		b.WriteString(generatePostgresTableHelpers(schema))

		singular := TableToStructName(schema.Table)
		exportNames = append(exportNames,
			fmt.Sprintf("list%ss", singular),
			fmt.Sprintf("get%s", singular),
			fmt.Sprintf("create%s", singular),
			fmt.Sprintf("update%s", singular),
			fmt.Sprintf("delete%s", singular),
		)
	}

	// closeDB — graceful shutdown
	b.WriteString("async function closeDB() {\n")
	b.WriteString("  await pool.end();\n")
	b.WriteString("}\n\n")

	// Module exports
	b.WriteString("module.exports = {\n")
	for i, name := range exportNames {
		b.WriteString(fmt.Sprintf("  %s", name))
		if i < len(exportNames)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("};\n")

	return b.String()
}

// generatePostgresTableHelpers generates async CRUD helper functions for a
// single table, using PostgreSQL $N numbered parameter placeholders.
func generatePostgresTableHelpers(schema manifest.Schema) string {
	var b strings.Builder

	table := schema.Table
	singular := TableToStructName(table)
	pkCol := findPKColumn(schema)

	// listXxx(limit = 50, offset = 0)
	b.WriteString(fmt.Sprintf("async function list%ss(limit = 50, offset = 0) {\n", singular))
	b.WriteString(fmt.Sprintf("  const { rows } = await pool.query('SELECT * FROM %s WHERE deleted_at IS NULL LIMIT $1 OFFSET $2', [limit, offset]);\n", table))
	b.WriteString("  return rows;\n")
	b.WriteString("}\n\n")

	// getXxx(id)
	b.WriteString(fmt.Sprintf("async function get%s(id) {\n", singular))
	b.WriteString(fmt.Sprintf("  const { rows } = await pool.query('SELECT * FROM %s WHERE %s = $1 AND deleted_at IS NULL', [id]);\n", table, pkCol))
	b.WriteString("  return rows[0];\n")
	b.WriteString("}\n\n")

	// createXxx(data) — uses nonAutoPrimaryColumns
	insertCols := nonAutoPrimaryColumns(schema)
	var filteredCols []manifest.Column
	for _, col := range insertCols {
		if col.Name == "created_at" || col.Name == "updated_at" || col.Name == "deleted_at" {
			continue
		}
		filteredCols = append(filteredCols, col)
	}
	insertCols = filteredCols
	colNamesList := columnNames(insertCols)

	placeholders := make([]string, len(insertCols))
	params := make([]string, len(insertCols))
	for i, col := range insertCols {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		params[i] = fmt.Sprintf("data.%s", col.Name)
	}

	b.WriteString(fmt.Sprintf("async function create%s(data) {\n", singular))
	b.WriteString(fmt.Sprintf("  const { rows } = await pool.query(\n"))
	b.WriteString(fmt.Sprintf("    'INSERT INTO %s (%s) VALUES (%s) RETURNING *',\n",
		table, colNamesList, strings.Join(placeholders, ", ")))
	b.WriteString(fmt.Sprintf("    [%s]\n", strings.Join(params, ", ")))
	b.WriteString("  );\n")
	b.WriteString("  return rows[0];\n")
	b.WriteString("}\n\n")

	// updateXxx(id, data) — uses nonPrimaryColumns for SET clause
	updateCols := nonPrimaryColumns(schema)
	var filteredUpdateCols []manifest.Column
	for _, col := range updateCols {
		if col.Name == "created_at" || col.Name == "updated_at" || col.Name == "deleted_at" {
			continue
		}
		filteredUpdateCols = append(filteredUpdateCols, col)
	}
	updateCols = filteredUpdateCols
	setClauses := make([]string, len(updateCols))
	updateParams := make([]string, len(updateCols))
	for i, col := range updateCols {
		setClauses[i] = fmt.Sprintf("%s = $%d", col.Name, i+1)
		updateParams[i] = fmt.Sprintf("data.%s", col.Name)
	}
	setClauses = append(setClauses, "updated_at = NOW()")
	// The id param is the last numbered param
	idParamNum := len(updateCols) + 1
	updateParams = append(updateParams, "id")

	b.WriteString(fmt.Sprintf("async function update%s(id, data) {\n", singular))
	b.WriteString(fmt.Sprintf("  const { rows } = await pool.query(\n"))
	b.WriteString(fmt.Sprintf("    'UPDATE %s SET %s WHERE %s = $%d RETURNING *',\n",
		table, strings.Join(setClauses, ", "), pkCol, idParamNum))
	b.WriteString(fmt.Sprintf("    [%s]\n", strings.Join(updateParams, ", ")))
	b.WriteString("  );\n")
	b.WriteString("  return rows[0];\n")
	b.WriteString("}\n\n")

	// deleteXxx(id) — soft delete
	b.WriteString(fmt.Sprintf("async function delete%s(id) {\n", singular))
	b.WriteString(fmt.Sprintf("  await pool.query('UPDATE %s SET deleted_at = NOW() WHERE %s = $1 AND deleted_at IS NULL', [id]);\n", table, pkCol))
	b.WriteString("}\n\n")

	return b.String()
}

// formatPostgresValue formats a Go value as a PostgreSQL literal.
func formatPostgresValue(v any) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case string:
		escaped := strings.ReplaceAll(val, "'", "''")
		return fmt.Sprintf("'%s'", escaped)
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case bool:
		return fmt.Sprintf("%t", val)
	default:
		return fmt.Sprintf("'%v'", v)
	}
}
