package export

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vibeserve/vibeserve/internal/manifest"
)

// RunFullstack generates a monorepo with Express.js backend + Next.js frontend.
//
//	project/
//	  backend/     ← Express.js (same as RunExpress)
//	  frontend/    ← Next.js admin panel (same as RunNext)
//	  package.json ← Root workspace
//	  README.md
func (e *Exporter) RunFullstack() error {
	m := e.manifest

	// Validate
	if err := manifest.Validate(m); err != nil {
		return fmt.Errorf("manifest validation: %w", err)
	}

	// Infer FKs
	m.Schemas = manifest.InferForeignKeys(m.Schemas)

	// Create root dir
	if err := os.MkdirAll(e.outDir, 0o755); err != nil {
		return fmt.Errorf("create dir: %w", err)
	}

	// Generate backend (Express.js)
	backendDir := filepath.Join(e.outDir, "backend")
	backendExp := NewExporter(m, backendDir)
	backendExp.SetVibeDir(e.vibeDir)
	backendExp.SetDBType(e.DBType())
	if e.typescript {
		backendExp.SetTypeScript(true)
	}
	if err := backendExp.RunExpress(); err != nil {
		return fmt.Errorf("backend export: %w", err)
	}

	// Generate frontend (Next.js)
	frontendDir := filepath.Join(e.outDir, "frontend")
	frontendExp := NewExporter(m, frontendDir)
	frontendExp.SetVibeDir(e.vibeDir)
	if err := frontendExp.RunNext(); err != nil {
		return fmt.Errorf("frontend export: %w", err)
	}

	// Root package.json (npm workspaces)
	rootPkg := generateRootPackageJSON(m.Name)
	if err := writeFile(filepath.Join(e.outDir, "package.json"), rootPkg); err != nil {
		return fmt.Errorf("write root package.json: %w", err)
	}

	// Root README
	rootReadme := generateFullstackREADME(m, e.DBType())
	if err := writeFile(filepath.Join(e.outDir, "README.md"), rootReadme); err != nil {
		return fmt.Errorf("write README: %w", err)
	}

	// Root .gitignore
	if err := writeFile(filepath.Join(e.outDir, ".gitignore"), "node_modules/\n.next/\ndist/\n.env\n.env.local\n*.db\n"); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}

	return nil
}

func generateRootPackageJSON(name string) string {
	return fmt.Sprintf(`{
  "name": "%s",
  "private": true,
  "workspaces": ["backend", "frontend"],
  "scripts": {
    "dev": "concurrently \"npm run dev:backend\" \"npm run dev:frontend\"",
    "dev:backend": "cd backend && npm run dev",
    "dev:frontend": "cd frontend && npm run dev",
    "install:all": "cd backend && npm install && cd ../frontend && npm install",
    "build": "cd frontend && npm run build",
    "start": "cd backend && npm start"
  },
  "devDependencies": {
    "concurrently": "^9.0.0"
  }
}
`, Slugify(name))
}

func generateFullstackREADME(m *manifest.Manifest, dbType string) string {
	name := m.Name
	if name == "" {
		name = "My App"
	}

	readme := fmt.Sprintf(`# %s

Full-stack application generated by VibeServe.

## Structure

`+"```"+`
%s/
  backend/     Express.js API server
  frontend/    Next.js admin panel
  package.json Root workspace
`+"```"+`

## Quick Start

`+"```"+`bash
# Install all dependencies
npm run install:all

# Start both backend and frontend
npm run dev
`+"```"+`

Backend runs at: http://localhost:3000
Frontend runs at: http://localhost:3001

`, name, Slugify(name))

	if dbType == "postgres" {
		readme += `## Database Setup

` + "```" + `bash
# Create PostgreSQL database and run migrations
psql -d your_database -f backend/schema.sql
psql -d your_database -f backend/seed.sql  # optional
` + "```" + `

Update ` + "`backend/.env`" + ` with your DATABASE_URL.

`
	}

	readme += fmt.Sprintf(`## API Documentation

- Swagger UI: http://localhost:3000/_swagger (when backend is running via vibeserve)
- OpenAPI spec: backend/openapi.yaml

## Tables

%d tables, %d routes

## Generated by

[VibeServe](https://github.com/ziquanc/vibeserve) — describe your API, get a running server.
`, len(m.Schemas), len(m.Routes))

	return readme
}
